apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-routes
spec:
  hosts:
    - api-location
  http:
  - route:
    - destination:
        host: api-location
        subset: prod
      weight: 0
    - destination:
        host: api-location
        subset: canary
      weight: 100