apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: api-routes
spec:
  destination:
    name: api-location
  route:
  - labels:
      version: prod
    weight: {{.Values.prodWeight}}
  - labels:
      version: canary
    weight: {{.Values.canaryWeight}}